// Generated by https://quicktype.io

export interface JSONResponse {
    count:    number;
    next:     string;
    previous: any;
    results:  Result[];
}

export interface Result {
    name: string;
    url:  string;
}
